version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-auth-service
    container_name: laravel-auth-app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - laravel-net

  mysql:
    image: mysql:5.7
    container_name: laravel-auth-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: auth_service
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge

volumes:
  dbdata:
